### PR TITLE
Do not skip whitespace after opening ( in string literals

### PR DESCRIPTION
**Pull request by jgajek**
Fixes parser bug described in https://github.com/jesparza/peepdf/pull/61

### CODE REVIEW

**Comment by jbremer** [comment]
Would this be a good time to setup unit testing for peepdf? :-)
Do you have a 'minimal' pdf for this by any chance?

**Comment by jgajek** [comment]
Well, it's not 'minimal', but here is a real PDF that exhibits this issue:

http://www.cci.health.wa.gov.au/docs/BB-1-Overview.pdf

**Comment by jbremer** [comment]
Sweet! I'll take it.

**Comment by jbremer** [comment]
Merged and added a unit test for it ;-) Interestingly enough getting 21% code coverage with just a single unit test, not bad.

**Comment by jbremer** [comment]
And last but not least, bumped to `0.3.3`.

**Comment by jgajek** [comment]
Thanks for your work in packaging it :)

For the unit test, perhaps it would be better to use manualAnalysis=True?  Unless you intentionally want to kick off automatic JS emulation.

**Comment by jbremer** [comment]
I guess that works, too. I'm just wondering though, does it really matter? And if so, should we not do the same in cuckoo?

**Comment by jgajek** [comment]
Yes, I think we should do the same in Cuckoo, at least by default. Perhaps
have an advanced option to turn on JS emulation -- it has the potential to
really slow down the analysis or go into an infinite loop.

**Pull request merged**
